<a href="https://colab.research.google.com/github/MirzaSaniya/Accessing-Python-Library-Saniya-Mirza/blob/main/Access_Python_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Import necessary libraries
import pandas as pd
import numpy as np

In [ ]:
# (a) Determine the shape, number of dimensions and type of
# elements in the numpy array arr
# (b) Determine the sum of elements in arr
# (c) Determine the mean of elements in arr
# (d) Create an array of the same shape as arr but filled with zeros
# (e) Create an array of the same shape as arr but filled with ones
# (f) Create an array of the same shape as arr but where all elements are squared values
# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot
arr = np.arange(15).reshape(3, 5)

# Answer for (a)
print('Shape of the numpy array arr is: ',arr.shape)
print('Number of dimensions of the numpy arr is: ',arr.ndim)
print('Type of elements in the numpy array arr is: ',arr.dtype)

# Answer for (b)
print('Sum of the numpy array arr is: ',arr.sum())

# Answer for (c)
print('Mean of the numpy array arr is: ',arr.mean())

# Answer for (d)
arr = np.zeros((3,5),dtype = np.int)
print('Array of the shape (3, 5) with values as zeroes')
print(arr)

# Answer for (e)
arr = np.ones((3,5), dtype = np.int)
print('Array of the shape (3, 5) with values as ones')
print(arr)

# Answer for (f)
arr = np.arange(15).reshape(3, 5)
print('Original Array of shape (3, 5)')
print(arr)
print('Array after squared values')
print(np.square(arr))

# Answer for (g)
arr = np.arange(1,10).reshape(3,3)
print('Array of the shape (3, 3)')
print(arr)
print('Array after multipying it with its transpose')
print(np.dot(arr, np.transpose(arr)))


Shape of the numpy array arr is:  (3, 5)
Number of dimensions of the numpy arr is:  2
Type of elements in the numpy array arr is:  int32
Sum of the numpy array arr is:  105
Mean of the numpy array arr is:  7.0
Array of the shape (3, 5) with values as zeroes
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Array of the shape (3, 5) with values as ones
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Original Array of shape (3, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Array after squared values
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]
Array of the shape (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after multipying it with its transpose
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


In [ ]:
# The following piece of code creates a DataFrame
# (a) Determine the shape of the dataframe
# (b) Print out all the columns of the dataframe
# (c) Print the 3rd element of the dataframe
# (d) Find the average of 'petal_width' where species is 'virginica'
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
# (f): What is the average value of sepal_length
# (g): What is the maximum value of sepal_width
# (h): What is the minimum value of petal_width
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df.head(10) #prints the first 10 rows

# Answer for (a)
print('The shape of the dataframe is:', df.shape)

# Answer for (b)
print('The column headers of the dataframe is:',df.columns.values)

# Answer for (c)
print('The third element of the dataframe is:')
print(df.iloc[3])

# Answer for (d)
print('The average of the petal_width where species is virginica is:', df['petal_width'][df['species'] == 'virginica'].mean())

# Answer for (e)
print('The maximum of sepal_width where species is setosa is:', df['sepal_width'][df['species'] == 'setosa'].max())

# Answer for (f)
print('The average for sepal_length is:', df['sepal_length'].mean())

# Answer for (g)
print('The maximum for sepal_width is:', df['sepal_width'].max())

# Answer for (h)
print('The minimum for petal_width is:', df['petal_width'].min())


The shape of the dataframe is: (150, 5)
The column headers of the dataframe is: ['sepal_length' 'sepal_width' 'petal_length' 'petal_width' 'species']
The third element of the dataframe is:
sepal_length       4.6
sepal_width        3.1
petal_length       1.5
petal_width        0.2
species         setosa
Name: 3, dtype: object
The average of the petal_width where species is virginica is: 2.026
The maximum of sepal_width where species is setosa is: 4.4
The average for sepal_length is: 5.843333333333335
The maximum for sepal_width is: 4.4
The minimum for petal_width is: 0.1
